Notas="""
Para lograr que la carpeta quede dentro de git debo pasar por consola "git init" (Repositorio de GIT Local)
Si quiero elegir una carpeta particular pongo"git init +nombre de carpeta"

Para agregar un archivo a una stage area (Previa al repositorio "To be comitted") uso el comando "git add +nombre del 
archivo" o bien para agregar todos juntos hago "git add ." 

Cuando tengo un archivo en to be comitted visual studio lo marca con una "A"

"git rm --cached <file>..." para sacar del to be comitted algun archivo

Para crear un punto de control "git commit -m "primer commit que hago"

(use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)

  



"""